accounts/passwords/urls.py
from django.contrib.auth import views
from django.urls import path
from django.urls import reverse_lazy

urlpatterns = [
    path('password_change/', views.PasswordChangeView.as_view(success_url=reverse_lazy("password:password_change_done")), name='password_change'),
    path('password_change_done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view(success_url=reverse_lazy("password:password_reset_done")), name='password_reset'), # Parola sıfırlamak için mail adresi
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'), # Mail adresine sıfırlama link gönderildi sayfası
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("password:password_reset_complete")), name='password_reset_confirm'), # Yeni mail parolası belirleme
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),  # Parola sıfırlama başarıyla tamamlandı sayfası
]

accounts/urls.py
from django.urls import path
from django.urls import  re_path
from products.views import UserProductHistoryView


from .views import AccountHomeView,AccountEmailActivateView,UserDetailUpdateView

urlpatterns = [
    path('', AccountHomeView.as_view(), name="home"),
    path('details/', UserDetailUpdateView.as_view(), name="user-update"),
    path('history/products/', UserProductHistoryView.as_view(), name="user-product-history"),

    re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name="email-activate"),
    re_path(r'^email/resend-activation/', AccountEmailActivateView.as_view(), name="resend-activation"),

]

carts/urls.py
from django.urls import path

from .views import cart_home,cart_update,checkout_home,checkout_done

urlpatterns = [
    path('', cart_home, name="home"),
    path('update/',cart_update, name="update"),
    path('checkout/', checkout_home, name="checkout"),
    path('checkout/success/', checkout_done, name="success"),

]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import home, about, contact
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from accounts.views import LoginView, RegisterView,GuestRegisterView
from django.views.generic import TemplateView,RedirectView
from django.contrib.auth.views import LogoutView
from carts.views import cart_detail_api_view
from billing.views import paymend_method_view,paymend_method_create_view
from marketing.views import MarketingPrefenceUpdateView,MailchimpWebhookView
from orders.views import LibraryView
from analytics.views import SalesView,SalesAjaxView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home,name="home"),
    path('about/', about, name="about"),
    # path('accounts/login/', RedirectView.as_view(url="/login")),
    path('accounts/', RedirectView.as_view(url="/account")),
    path('account/', include(('accounts.urls','account'),namespace="account")),
    path('accounts/', include(('accounts.passwords.urls',"password"),namespace='password')),
    path('contact/', contact,name="contact"),
    path('checkout/address/create/', checkout_address_create_view,name="checkout_address_create"),
    path('checkout/address/reuse/', checkout_address_reuse_view, name="checkout_address_reuse"),
    path('analytics/sales/', SalesView.as_view(), name="sales-analytics"),
    path('analytics/sales/data/', SalesAjaxView.as_view(), name="sales-analytics-data"),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('login/', LoginView.as_view(),name="login"),
    path('register/guest', GuestRegisterView.as_view(),name="guest_register"),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('library/', LibraryView.as_view(), name='library'),
    path('billing/payment-method/', paymend_method_view, name='billing-payment-method'),
    path('billing/payment-method/create/', paymend_method_create_view, name='billing-payment-method-endpoint'),
    path('cart/', include(('carts.urls', 'carts'), namespace='cart')),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('search/', include(('search.urls', 'search'), namespace='search')),
    path('settings/', RedirectView.as_view(url="/account")),
    path('settings/email/', MarketingPrefenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import EmailActivation,GuestEmail
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.auth import authenticate, login,get_user_model



User=get_user_model()

class ReactiveEmailForm(forms.Form):
    email=forms.EmailField()

    def clean_email(self):
        email=self.cleaned_data.get("email")
        qs=EmailActivation.objects.email_exists(email)
        if not qs.exists():
            register_link = reverse("register")
            msg = """
                    This email does not exits, would you like to  <a href="{link}">register</> ?
                  """.format(link=register_link)
            raise forms.ValidationError(mark_safe(msg))
        return email




   # Admin Paneli kullanıcı oluşturma
class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name','email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



class UserDetailChangeForm(forms.ModelForm):
    full_name=forms.CharField(label="Name",required=False,widget=forms.TextInput(attrs={'class':"form-control"}))
    class Meta:
        model=User
        fields=['full_name']

# Admin Paneli kullanıcı bilgileri değiştirme
class UserAdminChangeForm(forms.ModelForm):

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name','email', 'password','is_active', 'admin')

    def clean_password(self):
        return self.initial["password"]



class GuestForm(forms.ModelForm):
    class Meta:
        model=GuestEmail
        fields=[
            'email'
        ]

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(GuestForm,self).__init__(*args,**kwargs)

    def save(self, commit=True):
        obj = super(GuestForm, self).save(commit=False)
        if commit:
            obj.save()
            request=self.request
            request.session['guest_email_id'] = obj.id
        return obj


class LoginForm(forms.Form):
    email=forms.EmailField(required=False,label="Email")
    password=forms.CharField(required=False,widget=forms.PasswordInput)

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(LoginForm,self).__init__(*args,**kwargs)

    def clean(self):
        request=self.request
        data=self.cleaned_data
        email = data.get('email')
        password = data.get('password')

        qs=User.objects.filter(email=email)
        if qs.exists():
            not_active=qs.filter(is_active=False)
            if not_active.exists():
                link=reverse("account:resend-activation")
                reconfirm_msg="""Go to <a href="{resend_link}">resend confirmable email.</a>""".format(resend_link=link)
                confirm_email=EmailActivation.objects.filter(email=email)
                is_confirmable=confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1="Please check your email to confirm your account or "+reconfirm_msg.lower()
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists=EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2="Email not confirmed. "+reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))

                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError("This user is inactive.")

        user = authenticate(request, email=email, password=password)
        if user is None:
            raise forms.ValidationError("Geçersiz giriş bilgileri")
        else:
            login(request, user)
        self.user=user
        return data


class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name','email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Parolalar Eşleşmiyor")
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active=False
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import redirect,render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import CreateView,FormView,DetailView,View,UpdateView
from django.views.generic.edit import FormMixin
from .forms import LoginForm,RegisterForm,GuestForm,ReactiveEmailForm,UserDetailChangeForm
from ecommerce.mixins import NextUrlMixin,RequestFormAttachMixin

from django.urls import reverse
from django.utils.safestring import mark_safe

from .models import EmailActivation


# Yöntem 2 ,
class AccountHomeView(LoginRequiredMixin,DetailView):
    template_name = "accounts/home.html"
    def get_object(self):
        return self.request.user


class AccountEmailActivateView(FormMixin,View):
    success_url = "/login/"
    form_class = ReactiveEmailForm
    key=None
    def get(self,request,key=None,*args,**kwargs):
        self.key=key
        if key is not None:
            qs=EmailActivation.objects.filter(key__iexact=key)
            confirmable_qs=qs.confirmable()
            if confirmable_qs.exists()==1:
                obj=confirmable_qs.first()
                obj.activate()
                messages.success(request,"Your email has been corfirmed.Please login.")
                return redirect('login')
            else:
                activate_qs=qs.filter(activated=True)
                if activate_qs.exists():
                    reset_link=reverse("accounts:password_reset")
                    msg="""
                    Your email has already been confirmed.
                     Do you need to <a href="{link}"> reset your password</a>?
                    """"".format(link=reset_link)
                    messages.success(request,mark_safe(msg))
                    return redirect("login")
        context={"form":self.get_form(),'key':key}
        return render(request,"registration/activation-error.html",context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


    def form_valid(self, form):
        # Here, we would record the user's interest using the message
        # passed in form.cleaned_data['message']
        msg = "Activation link send , please check your email."
        request=self.request
        messages.success(request,msg)
        email=form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user=obj.user
        new_activation=EmailActivation.objects.create(user=user,email=email)
        new_activation.send_activation()

        return super(AccountEmailActivateView,self).form_valid(form)

    def form_invalid(self, form):

        context = {"form": self.get_form(),'key':self.key}
        return render(self.request, "registration/activation-error.html", context)



class GuestRegisterView(NextUrlMixin,RequestFormAttachMixin,CreateView):
    form_class = GuestForm
    default_next = "/register/"

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)


class LoginView(NextUrlMixin,RequestFormAttachMixin,FormView):
    form_class = LoginForm
    template_name = "accounts/login.html"
    success_url = "/"
    default_next = "/"

    def form_valid(self, form):
        next_path=self.get_next_url()
        return redirect(next_path)




class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = "/login/"

class UserDetailUpdateView(LoginRequiredMixin,UpdateView):
    form_class =UserDetailChangeForm
    template_name = "accounts/detail-update-view.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self,*args, **kwargs):
        content=super(UserDetailUpdateView,self).get_context_data(*args,**kwargs)
        content['title']="Change Your Account  Details"
        return content

    def get_success_url(self):
        return reverse("account:home")

templates/accounts/detail-update-view.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-12 col-md-6 mx-auto">
        {% if title %}
            <h2 class="my-3"> {{ title }}</h2>
        {% endif %}

        <form method="POST" action="{% if action_url %}{{ action_url }}{% endif %}">
            {% csrf_token %}

            {% if next_url %}
                <input type="hidden"  name="next" value="{{ next_url }}">
            {% endif %}
            {{ form.as_p }}

            <label for="email">Email</label>
            <input type="text" id="email" class="form-control disabled" value="{{ request.user.email }}" disabled>
            <span class="help-text">Cannot change email</span>
            <br>
            <button type="submit" class="btn btn-primary mt-3">Kaydet</button>
            <a href="{% url 'password:password_change' %}">Change Password</a>
        </form>
    </div>


{% endblock %}

templates/accounts/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">

        <div class="col-12">
            <h1>Account</h1>
            <hr>
        </div>

        <div class="col-12 col-md-3 my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Support</h5>
                    <div class="list-group">
                        <a href="{% url 'about' %}" class="list-group-item">About</a>
                        <a href="{% url 'contact' %}" class="list-group-item">Contact</a>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-12 col-md-3  my-3" id="billing">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Billing</h5>
                    <div class="list-group">
                        <a href="{% url 'orders:list' %}" class="list-group-item">Orders</a>
                        <a href="{% url 'billing-payment-method' %}" class="list-group-item">Payment Methods</a>
                        <a href="{% url 'about' %}" class="list-group-item">Addresses</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-3  my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Account Details</h5>
                    <div class="list-group">
                        <a href="{% url 'account:user-update' %}" class="list-group-item">Update Details</a>
                        <a href="{% url 'password:password_change' %}" class="list-group-item">Change Password</a>
                        <a href="{% url 'library' %}" class="list-group-item">Library</a>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-12 col-md-3  my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Configuration</h5>
                    <div class="list-group">
                        <a href="{% url 'marketing-pref'  %}" class="list-group-item">Email Marketing</a>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-12 col-md-3  my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">History</h5>
                         <div class="list-group">
                        <a href="{% url 'account:user-product-history'  %}" class="list-group-item">Products</a>
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron text-center">
    <h1>Login</h1>
    </div>

    <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Gönder</button>
</form>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}


{% block content %}
    <div class="jumbotron text-center">
    <h1>Register</h1>
    </div>


<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Kayıt Ol</button>
</form>

{% endblock %}